# Generated by Django 3.2.8 on 2021-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='admin', max_length=40),
        ),
    ]
