# Generated by Django 3.2.8 on 2021-10-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20211007_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.ImageField(default='404.jpg', upload_to='images/'),
        ),
    ]
